### ISSUE TITLE
Allow multiple UHCs to be run on the same server

### ISSUE THREAD

**Issue by ghost** [DrHenchman/uhc-pack#15]
Upon running /function uhc_pack:setup no book is given to the player.

**Comment by MantriXxD** [comment]
This datapack cannot run more than once in a world, it just bugs out, not giving the book is one of the bugs. I would advise to create a function or item to obtain this book manually

Other than that, for enhancement please add timestamps longer than 100 minutes and destroy the previous lobby if a new one is going to be generated, or just tp there after every setup.

**Comment by DrHenchman** [comment]
I'm so sorry for not responding before now. I must have not had my email notifications set up correctly.

Would you be able to elaborate on the use cases for running multiple UHCs in the same world? Normally, I have always seen a single UHC run in a world and you generate a new world for a new UHC.

**Comment by DrHenchman** [comment]
Timed out
