### ISSUE TITLE
Add tooltips in the configuration book for all the options

### ISSUE THREAD

**Issue by DrHenchman** [DrHenchman/uhc-pack#20]
Currently you just need to figure out what things do. It would be good to properly document what they in a tooltip when hovering over the text for the option

**Comment by PhotonBursted** [comment]
This one is in the works, I'll wait with doing the pull request until #22 is resolved (as that one adds an option to the book, so it's probably handier to add tooltips to that one in the same request)

**Comment by DrHenchman** [comment]
Sounds great. Looking forward to it.
