### ISSUE TITLE
[Lobby] Show the amount of competitors

### ISSUE THREAD

**Issue by PhotonBursted** [DrHenchman/uhc-pack#21]
Since we're counting manually right now, it might be handy to have a way to tell how many people are up for competing in the game. This should make it a lot easier to divide everyone up into the right amount of teams.

Ideas for this:
 - Sidebar scoreboard
 - A piece of text on that middle statue(?)
 - Next (or close) to the team count selector in the control book

**Comment by PhotonBursted** [comment]
Now that I think about it, the "sidebar scoreboard" idea might actually interfere with #17. It would have to be merged into that scoreboard then I guess, which might look kind of messy

**Comment by DrHenchman** [comment]
Great idea. I think that this could be implemented separately to #17. This is probably the easier of the 2 tickets to implement. It will just require #17 to take into account the implementation of this ticket.

If you are interested in implementing, feel free to send a pull request.

**Comment by PhotonBursted** [comment]
Looking into this one, looks like the second option is sadly not practically doable. Entities don't resolve the text in their custom names, so the only way the entity would get an updated name would be with if statements that give it a specific name according to the score. This has the obvious downside of lots of copy pasting.

Adding it to the book would also have issues, as resolution only happens on first opening; it'd be better, and at least _sometimes_ up to date, but not ideal. There's also not much space on that page, so there's that.

In the end, I guess a scoreboard will have to do?
Either that or a wall of signs, which would be more organized (everything has a fixed place of its own), and have more options in terms of styling, but would obviously be less visible than a sidebar

**Comment by DrHenchman** [comment]
I think having it in a sidebar scoreboard is the way to go
