### ISSUE TITLE
Book option toggle alignment

### ISSUE THREAD

**Issue by PhotonBursted** [DrHenchman/uhc-pack#32]
I noticed as I went through the book that the interactive toggles (talking especially about the "more options" section here) are placed after their labels, and since those labels obviously vary in length, every toggle is in a different location.

**Comment by PhotonBursted** [comment]
...this is probably related to #18 as well, but just thought I'd give it a separate mention :)

**Comment by DrHenchman** [comment]
Thanks for the feedback. I'm going to merge this with #18 as it would be great to fix them at the same time.
