### ISSUE TITLE
Make border shrink start and duration configurable per 10 minutes

### ISSUE THREAD

**Issue by rdroog** [DrHenchman/uhc-pack#72]
**Is your feature request related to a problem? Please describe.**
For us 20 and 40 minutes shrinking duration is a bit too fast and slow.

**Describe the solution you'd like**
Instead of being able to only set the border shrink start and duration per 20 minutes, it should be configurable per 10 minutes.

**Describe alternatives you've considered**
We have tried 20 and 40 minutes, but 30 minutes is perfect. And it's a small effort to make both settings configurable per 10 minutes, which gives a bit more freedom in playbility.

**Comment by DrHenchman** [comment]
Fixed in v0.26

**Comment by DrHenchman** [comment]
Not sure if you were planning to make any additional changes in the short term. If you are, I'll hold off on cutting the v0.26 version

**Comment by rdroog** [comment]
> Not sure if you were planning to make any additional changes in the short term. If you are, I'll hold off on cutting the v0.26 version

We have a few ideas, I'll see what I/we would like to implement in the weekend. But no need to wait too long, I can build my own datapack and we can use that in the meantime.
