### ISSUE TITLE
You can select the number of teams as 1 but randomizing requires at least 2 teams

### ISSUE THREAD

**Issue by rdroog** [DrHenchman/uhc-pack#74]
**Describe the bug**
If you want to start a practice game with only 1 team, randomizing teams won't work - an error is produced. No other setting can be successfully changed anymore. 

**To Reproduce**
1. Create new UHC world
2. Set teams to only 1 team
3. Randomize teams

Result: error occurs, team is not randomized, no other settings can be changed anymore.

**Expected behavior**
Error doesn't occur, other settings are still changeable, everyone is in the same team.

**Environment (please complete the following information):**
 - Minecraft server type: Vanilla
 - Minecraft version: 1.16.5
 - Datapack version: 0.25

**Comment by DrHenchman** [comment]
If you are testing a UHC by yourself (you are the only player in the world) you can just click start, you don't need to put yourself into a team.

**Comment by DrHenchman** [comment]
The preferred fix is to modify https://github.com/DrHenchman/uhc-pack/blob/master/data/uhc_pack/functions/lobby/update_options.mcfunction#L35 to prevent setting the number of teams to 1.

**Comment by DrHenchman** [comment]
Fixed in v0.26
