### ISSUE TITLE
[1.19] Storage data and objectives contents not retrieved in options book

### ISSUE THREAD

**Issue by MultimedYam** [DrHenchman/uhc-pack#82]
It appears that in 1.19 score objectives are no longer being retrieved for rendering in the options book.
These data elements are available and modifiable, just not in the lobby options book.

See picture:
- Options toggles are missing
- Time variables are missing
![image](https://user-images.githubusercontent.com/6081942/179350548-915cf1c3-bb34-4782-a3a1-6284a920f696.png)

Did Mojang sneakily change something in this recent update?

**Comment by CactusPuppy** [comment]
Confirming that this is also a problem in 1.18.2 (somehow?)
![image](https://user-images.githubusercontent.com/10406383/179386198-98de2e5b-4fe4-4fb7-863f-39dd2edc3c34.png)
Version:
![image](https://user-images.githubusercontent.com/10406383/179386210-dad27ba5-a1a2-4e77-a422-b97716aa5b13.png)

**Comment by MultimedYam** [comment]
This appears to be a Paper configuration that turns off component resolving by default, as it has some unfortunate use cases.
In the global paper configuration you have to set this setting to `true`
```
item-validation:
  resolve-selectors-in-books: false
```

**Comment by CactusPuppy** [comment]
> This appears to be a Paper configuration that turns off component resolving by default, as it has some unfortunate use cases. In the global paper configuration you have to set this setting to `true`
> 
> ```
> item-validation:
>   resolve-selectors-in-books: false
> ```

Ah, I figured Paper was messing with it somehow. Thanks for confirming.
